### PR TITLE
fix: menu component hardening — icon sizing, item density, section headings

### LINKED ISSUE #925: Hardening: Menu Components
## How This Works

Each component has a checkbox. Check it off when **all** findings for that component are resolved.

Findings are listed under each component with a severity tag:
- **P0** = broken, crash, doesn't render
- **P1** = visual mismatch, quality gap, a11y violation
- **P2** = polish, cosmetic, missing story

**When you fix something:** create a PR, link it next to the finding, check off the finding. When all findings for a component are done, check the component box.

---

### XDSDropdownMenu

- ~P1: Gap between the arrow icon and label is larger than on WWW (8px on OSS, 4px on WWW)~ — *icon and button placements in WWW are inconsistent; keeping 8px as the consistent default*
- ~P1: Using a different icon than WWW (triangle on WWW)~ — *parity delta (needs internal theme with brand icons), moved to gaps*
- [ ] P1: Menu item sizing should adjust based on the size of the dropdown menu (e.g. menu items should use 4px top/bottom padding when the dropdown is size md or sm)
- [ ] P1: Menu sections are using dividers on OSS instead of labels as on WWW
- ~P1: Button padding should be adjust for sm, md, and lg sizing — width:height ratio appears off balance for smaller buttons~ — *needs specific recommendations, moved to gaps*
- [ ] P1: Icon in the "Icon with Label" example is too large
- ~P1: Needs to support a destructive action variant for other internal library parity~ — *parity delta, moved to gaps*
- ~P2: Sub-menu support is missing — no Storybook example, unclear if implemented~ — *gap issue, not hardening*

### XDSMoreMenu

- [ ] P1: Sections are using dividers on OSS instead of labels as on WWW
- [ ] P1: Needs to support custom icons, not just the three-dots icon — *already implemented, needs storybook story*

### PR DESCRIPTION
**Pull request by cixzhang**
Fixes from hardening issue #925 for DropdownMenu and MoreMenu.

### Button icon sizing
- Wraps the `icon` slot in XDSButton with a constraining span sized per button size (sm→16px, md→20px, lg→20px)
- Adds `[data-xds='button-icon'] > svg { width: 100%; height: 100% }` in reset.css so raw SVG components (e.g. heroicons) scale correctly
- Fixes: **Icon in 'Icon with Label' example is too large**

### Size-aware menu item padding
- Adds `itemSizeStyles` to both XDSDropdownMenu and XDSMoreMenu
- sm/md triggers → 4px block, 8px inline padding on items
- lg triggers → 8px all around (current default)
- Derives menu density from the trigger button's `size` prop
- Fixes: **Menu item sizing should adjust based on the size of the dropdown menu**

### Section headings instead of dividers
- Replaces `XDSDivider label={title}` with inline section heading labels
- Section titles now render as small secondary text above the group — no divider lines
- Applied to both XDSDropdownMenu and XDSMoreMenu
- Fixes: **Menu sections are using dividers on OSS instead of labels**

### MoreMenu custom icon story
- Adds `CustomIcon` story demonstrating `icon` prop override (already implemented in code, was just missing a story)
- Fixes: **Needs to support custom icons, not just the three-dots icon**

Closes #925

### CODE REVIEW

File: packages/core/src/Button/XDSButton.tsx [hunk 1]
```diff
@@ -135,6 +141,16 @@ const sizeStyles = stylex.create({
   },
 });
 
+/**
+ * Icon size per button size.
+ * Matches XDSIcon sizing: sm=16px, md/lg=20px.
+ */
+const iconSizeStyles = stylex.create({
+  sm: {width: 16, height: 16},
+  md: {width: 20, height: 20},
```
Comment (cixzhang) [inline packages/core/src/Button/XDSButton.tsx]: Md buttons should use 16px icons

File: packages/core/src/Button/XDSButton.tsx [hunk 2]
```diff
@@ -523,7 +539,13 @@ export function XDSButton({
       <span
         {...stylex.props(styles.contentWrapper)}
         aria-hidden={isLoadingState || undefined}>
-        {icon}
+        {icon && (
+          <span
+            data-xds="button-icon"
```
Comment (cixzhang) [inline packages/core/src/Button/XDSButton.tsx]: Don't need this data-XDS

File: packages/core/src/DropdownMenu/XDSDropdownMenu.tsx [hunk 3]
```diff
@@ -41,6 +41,25 @@ import {
...
+ * sm/md triggers → tighter vertical padding (4px block, 8px inline)
+ * lg triggers → standard padding (8px all around, inherited from base item style)
+ */
+const itemSizeStyles = stylex.create({
+  sm: {
+    paddingBlock: spacingVars['--spacing-1'],
+    paddingInline: spacingVars['--spacing-2'],
+  },
+  md: {
+    paddingBlock: spacingVars['--spacing-1'],
```
Comment (cixzhang) [inline packages/core/src/DropdownMenu/XDSDropdownMenu.tsx]: Treat medium as default item padding

File: packages/core/src/MoreMenu/XDSMoreMenu.tsx [hunk 4]
```diff
@@ -52,6 +52,25 @@ import {xdsClassName, mergeProps} from '../utils';
...
+ * sm/md triggers → tighter vertical padding (4px block, 8px inline)
+ * lg triggers → standard padding (8px all around, inherited from base item style)
+ */
+const itemSizeStyles = stylex.create({
+  sm: {
+    paddingBlock: spacingVars['--spacing-1'],
+    paddingInline: spacingVars['--spacing-2'],
+  },
+  md: {
+    paddingBlock: spacingVars['--spacing-1'],
```
Comment (cixzhang) [inline packages/core/src/MoreMenu/XDSMoreMenu.tsx]: Same here, use the standard item for medium

File: packages/core/src/Button/XDSButton.tsx [hunk 5]
```diff
@@ -135,6 +141,16 @@ const sizeStyles = stylex.create({
   },
 });
 
+/**
+ * Icon size per button size.
+ * Matches XDSIcon sizing: sm/md=16px, lg=20px.
+ */
+const iconSizeStyles = stylex.create({
+  sm: {width: 16, height: 16},
```
Comment (cixzhang) [inline packages/core/src/Button/XDSButton.tsx]: Also font size for font icons?
