### PR TITLE
fix(topnav): use Popover API + CSS anchor positioning for mega menu

### LINKED ISSUE #411: Eliminate z-index stacking — use top layer (Popover API) for all overlays
## Problem

PRs #377, #378, and #379 reveal a pattern where `XDSTopNavMegaMenu` uses manual `z-index` and `position: absolute` to layer its panel above surrounding content. This led to a cascade of fixes — adding `z-index: 100` to nav sections so they wouldn't get covered by the mega menu's backdrop, then removing the backdrop entirely to avoid the complexity.

The root cause: the mega menu panel isn't using the top layer. XDS already has `useXDSLayer` which uses the Popover API (`showPopover()` / `popover="auto"|"manual"`), promoting elements to the browser's top layer. Elements in the top layer render above everything else without needing `z-index` at all.

## Current z-index usage in `packages/core/src/`

| File | z-index | Purpose |
|------|---------|---------|
| `AppShell` | 9999 | Skip-to-content link |
| `AppShell` | 100, 101 | Mobile overlay + backdrop |
| `AppShell` | 10 | Sticky header |
| `TopNavMegaMenu` | 100 | Mega menu panel |
| Various inputs | 1 | Internal layering (checkbox, radio, slider, etc.) |

The `z-index: 1` cases are fine — they're local stacking within a component. The problem is the **100-level values** used for overlays and panels that should be in the top layer instead.

## What needs to happen

1. **`XDSTopNavMegaMenu`** — Refactor to use `useXDSLayer` (or a variant of it) instead of manual `position: absolute` + `z-index: 100`. The panel should be promoted to the top layer via the Popover API.

2. **`XDSAppShell` mobile overlay** — The mobile side nav overlay and backdrop use `position: fixed` + `z-index: 100/101`. These should also use the top layer (either Popover API or `<dialog>` with `showModal()`).

3. **Audit remaining z-index > 1** — After fixing the above, audit for any remaining high z-index values that indicate manual stacking instead of top layer usage.

## Why this matters

- **z-index is fragile.** It breaks as soon as a consumer creates a stacking context. Top layer is immune to this.
- **Composability.** Components shouldn't need to know about each other's z-index values to layer correctly.
- **We already have the infrastructure.** `useXDSLayer` does this correctly — the mega menu just didn't use it.

## Related PRs

- #377 — Added z-index to nav (wrong fix)
- #378 — Moved z-index to nav sections (less wrong, still wrong)
- #379 — Removed backdrop, coordinated styles (workaround)
- #356 — Original mega menu unified card appearance
- #354 — XDSTopNavMegaMenu component

### PR DESCRIPTION
**Pull request by cixzhang**
## Problem

The mega menu panel used manual `position: absolute` + `z-index: 100` for layering, which triggered a cascade of z-index band-aids (#377, #378, #379). This is fragile — any consumer stacking context can break it.

XDS already has proper top layer infrastructure (`useXDSLayer` uses the Popover API), but the mega menu bypassed it entirely.

## Fix

Replace manual z-index stacking with the browser's top layer:

1. **Popover API** — Panel uses `popover="manual"` + `showPopover()`/`hidePopover()`. Promoted to the top layer automatically — renders above everything without z-index.

2. **CSS anchor positioning** — Panel anchors to the nearest positioned ancestor (the nav wrapper div) using `position-anchor` + `anchor()` functions. Replaces `position: absolute` + `top: 100%` + `left: 0` + `right: 0`.

3. **Mouse event bridging** — Since top layer elements are outside the DOM hierarchy for mouse events, added `onMouseEnter`/`onMouseLeave` on the panel itself. Without this, mousing from trigger → panel would fire `onMouseLeave` on the wrapper and close the menu.

4. **Popover toggle sync** — Listens for native `toggle` events to sync popover state back to React.

### What changed

| Before | After |
|--------|-------|
| `position: absolute` + `z-index: 100` | `popover="manual"` (top layer) |
| Panel is DOM child of wrapper | Panel is in top layer, positioned via CSS anchors |
| Mouse events flow through DOM hierarchy | Explicit mouse handlers on both wrapper and panel |
| Consumers need `position: relative` wrapper for positioning | Consumers need `position: relative` wrapper as CSS anchor |

### z-index audit (after this PR)

No z-index values remain in `XDSTopNavMegaMenu`. Remaining z-index in `packages/core/src/`:

| Component | z-index | Status |
|-----------|---------|--------|
| AppShell (skip-to-content) | 9999 | Fine — a11y skip link |
| AppShell (mobile overlay) | 100/101 | Being fixed in #341 |
| AppShell (sticky header) | 10 | Fine — sticky scroll overlap |
| Various inputs | 1 | Fine — local internal stacking |

## Test Plan

- ✅ All 1071 tests pass
- ✅ Build passes
- ✅ Lint clean
- ✅ No new TypeScript errors
- API unchanged — no breaking changes for consumers

Closes #411

## Related

- #377 — Added z-index to nav (wrong fix)
- #378 — Moved z-index to nav sections (less wrong)
- #379 — Removed backdrop (workaround)
- #354 — Original mega menu introduction
- #341 — MobileNav (separate top layer fix needed)

### CODE REVIEW

File: packages/core/src/TopNav/XDSTopNavMegaMenu.tsx [hunk 1]
```diff
@@ -1,17 +1,28 @@
...
+ *
  * SYNC: When modified, update these files to stay in sync:
  * - /packages/core/src/TopNav/README.md
  * - /packages/core/src/TopNav/index.ts
  */
 
 'use client';
 
-import {useCallback, useEffect, useRef, useState, type ReactNode} from 'react';
+import {
```
Comment (cixzhang) [inline packages/core/src/TopNav/XDSTopNavMegaMenu.tsx]: This isn't using useXDSLayer when I expected it to. That should probably eliminate most of the extra behaviors we needed to add around mouse event handling. More ideally though, we should be using useXDSPopover or XDSPopover with custom trigger and anchor refs.

File: packages/core/src/TopNav/XDSTopNavMegaMenu.tsx [hunk 2]
```diff
@@ -78,29 +87,31 @@ const styles = stylex.create({
...
-    // Top border provides a subtle divider between the nav bar and panel
-    // while keeping them visually connected as one card.
     borderTop: `1px solid ${colorVars['--color-divider']}`,
     borderTopLeftRadius: 0,
     borderTopRightRadius: 0,
     borderBottomLeftRadius: radiusVars['--radius-container'],
     borderBottomRightRadius: radiusVars['--radius-container'],
-    // Shadow wraps the panel; the wrapper handles the nav bar's card chrome.
-    // Together they create a unified card appearance without a backdrop overlay.
     boxShadow: `0 8px 24px rgba(0, 0, 0, 0.12), 0 2px 8px rgba(0, 0, 0, 0.08)`,
```
Comment (cixzhang) [inline packages/core/src/TopNav/XDSTopNavMegaMenu.tsx]: This should use elevationVars.

File: packages/core/src/TopNav/XDSTopNavMegaMenu.tsx [hunk 3]
```diff
@@ -78,29 +87,31 @@ const styles = stylex.create({
...
-    left: 0,
-    right: 0,
-    zIndex: 100,
+    // Reset popover defaults
+    margin: 0,
+    padding: 0,
+    borderWidth: 0,
+    borderStyle: 'none',
+    // Visual styles
     backgroundColor: colorVars['--color-surface'],
```
Comment (cixzhang) [inline packages/core/src/TopNav/XDSTopNavMegaMenu.tsx]: Since this is a popover, it should be using the popover background which is slightly different in dark mode.

**Comment by cixzhang** [comment]
Can we have proper stories for the mega menu and top nav menu so they can be inspected for regressions?

**Comment by cixzhang** [comment]
Added dedicated Storybook stories for XDSTopNavMenu and XDSTopNavMegaMenu:

- **Default** — Single nav menu with 4 items (icon + title + description)
- **Multiple Menus** — Two nav menus side by side
- **Mega Menu** — Full-width with items grid + featured content
- **Mega Menu (Simple)** — Single column, no featured content

These will show up in the Storybook preview once CI deploys.
