### PR TITLE
fix(AppShell): move sticky bg to targetable elements, add class names to wrappers

### LINKED ISSUE #1762: feat(AppShell): support translucent top nav with backdrop blur
## Problem

When using `XDSAppShell` with `height="auto"` (sticky header), the top nav header and its parent sticky wrapper both get opaque background colors. There's no way to make the top nav translucent with a backdrop blur effect without overriding multiple internal elements via CSS.

## Current workaround (docsite)

```css
.xds-layout-header {
  background: color-mix(in srgb, var(--color-background-surface) 80%, transparent) !important;
  backdrop-filter: blur(12px);
}
:has(> .xds-layout-header) {
  background: transparent !important;
}
```

Two issues:
1. The sticky wrapper div (parent of `.xds-layout-header`) gets `stickyBgStyle` which is opaque — must be overridden separately
2. Requires `!important` to beat StyleX inline styles

## Suggestion

Add a `topNavStyle` or `translucent` option (perhaps on the variant or as a separate prop) that applies translucent background + backdrop-filter to the header area natively, including making the sticky wrapper transparent.

### PR DESCRIPTION
**Pull request by cixzhang**
## Summary

The sticky wrapper divs in auto height mode had opaque backgrounds AND no class names — making it impossible to create translucent header effects without `!important` and `:has()` hacks.

### Before
```
<div [sticky wrapper — opaque bg, NO class name]>          ← untargetable
  <XDSLayoutHeader .xds-layout-header [also opaque bg]>   ← targetable but parent blocks it
```

Override required:
```css
.xds-layout-header {
  background: color-mix(...) !important;
  backdrop-filter: blur(12px);
}
:has(> .xds-layout-header) {
  background: transparent !important;
}
```

### After
```
<div .xds-app-shell-header [structural only — no bg]>     ← targetable, transparent
  <XDSLayoutHeader .xds-layout-header [owns the bg]>      ← single override target
```

Override becomes:
```css
@scope .xds-app-shell {
  .xds-layout-header {
    background: color-mix(in srgb, var(--color-background-surface) 80%, transparent);
    backdrop-filter: blur(12px);
  }
}
```

No `!important`, no `:has()`.

### Changes
- **XDSAppShell.tsx**: Move `stickyBgStyle` from wrapper divs onto `XDSLayoutHeader` / `XDSLayoutPanel` (in auto mode). Add `xdsClassName('app-shell-header')` and `xdsClassName('app-shell-sidenav')` to the wrappers.
- **AppShell.doc.mjs**: Document new theming targets.

Fixes #1762

---

### CODE REVIEW

File: packages/core/src/AppShell/XDSAppShell.tsx [hunk 1]
```diff
@@ -662,7 +662,7 @@ export function XDSAppShell({
       <XDSLayoutHeader
         padding={0}
         hasDivider={navHasDividers && hasTopNav}
-        xstyle={navAreaStyle}>
+        xstyle={isAuto ? stickyBgStyle : navAreaStyle}>
         {hasBanner && <div {...stylex.props(styles.banner)}>{banner}</div>}
```
Comment (cixzhang) [inline packages/core/src/AppShell/XDSAppShell.tsx]: Main intention here is for the banner to sit over an opaque background so we can actually remove the sticky bg background from the layout header and move it here.

File: packages/core/src/AppShell/XDSAppShell.tsx [hunk 2]
```diff
@@ -707,7 +710,11 @@ export function XDSAppShell({
...
       <div {...stylex.props(styles.sideNavAutoWrapper)}>
-        <div {...stylex.props(styles.sideNavSticky, stickyBgStyle)}>
+        <div
+          {...mergeProps(
+            xdsClassName('app-shell-sidenav'),
+            stylex.props(styles.sideNavSticky),
+          )}>
           {sideNavPanel}
         </div>
       </div>
```
Comment (cixzhang) [inline packages/core/src/AppShell/XDSAppShell.tsx]: Could we condense this to a single DOM element? Why do we need 2? 

This is the wrapper that applies sticky, so if we can, avoid applying any BG here and apply it on the inner component.

File: packages/core/src/AppShell/XDSAppShell.tsx
Comment (cixzhang) [inline packages/core/src/AppShell/XDSAppShell.tsx:712]: In the current core, the classname application is uneven since it'll miss this branch.

Comment (cixzhang) [inline packages/core/src/AppShell/XDSAppShell.tsx:705]: Since this is the inner component, we would apply the bg color here, then this also needs `className=xdsClassName('app-shell-sidenav')`. I think setting here makes more sense so it'll apply to all branches of rendering this panel.

File: packages/core/src/AppShell/XDSAppShell.tsx [hunk 3]
```diff
@@ -676,9 +676,9 @@ export function XDSAppShell({
     headerInner != null ? (
       <div
         ref={headerRef}
-        {...stylex.props(
-          isAuto && styles.headerSticky,
-          isAuto && stickyBgStyle,
+        {...mergeProps(
+          xdsClassName('app-shell-header'),
+          stylex.props(isAuto && styles.headerSticky),
```
Comment (cixzhang) [inline packages/core/src/AppShell/XDSAppShell.tsx]: Since this is targetable, we can make this the element that has the stickyBgStyle.

File: packages/core/src/AppShell/XDSAppShell.tsx [hunk 4]
```diff
@@ -759,14 +766,14 @@ export function XDSAppShell({
...
         )}>
         <XDSLayoutHeader
           padding={0}
           hasDivider={navHasDividers}
-          xstyle={navAreaStyle}>
+          xstyle={isAuto ? stickyBgStyle : navAreaStyle}>
```
Comment (cixzhang) [inline packages/core/src/AppShell/XDSAppShell.tsx]: Since app-shell-header is targettable, we should move the stickyBgStyle there.
