### PR TITLE
fix(Chat): harden chat components — scroll button, drawer animation, status, bubbles, stories

### LINKED ISSUE #1226: Hardening: AI Chat Components (17)
## How This Works

Each component has a checkbox. Check it off when **all** findings for that component are resolved.

Findings are listed under each component with a severity tag:
- **P0** = broken, crash, doesn't render
- **P1** = visual mismatch, quality gap, a11y violation
- **P2** = polish, cosmetic, missing story

**When you fix something:** create a PR, link it next to the finding, check off the finding. When all findings for a component are done, check the component box.

---

### XDSChatComposer

- [ ] P1: "With Attachments" example shows an empty toolbar above the text area — toolbar should not render when empty ([Storybook](https://studious-broccoli-o7e61n3.pages.github.io/storybook/index.html?path=/story/chat-xdschatcomposer--with-attachments))
- [ ] P1: Clicking anywhere in the composer should focus the textarea. Exceptions: clicking buttons (top toolbar, footer actions, submit button) or elements that render outside the composer (attachment drawer, error/status messages)
- [ ] P2: Storybook examples should include an optional flat microphone button to the left of the submit button
- [ ] P1: "Full Featured" example should match the ideal use case: top toolbar needs reference (@ icon) and attachment (paperclip icon) buttons, footer actions need "Auto" and "Settings" dropdown menus, and submit area needs the microphone button to the left of the submit button ([Storybook](https://studious-broccoli-o7e61n3.pages.github.io/storybook/index.html?path=/story/chat-xdschatcomposer--full-featured))
- [ ] P1: Spacing between attachment tokens should be `--spacing-1` (currently `--spacing-2`)
- [ ] P1: Attachment tokens should be removable — examples need a clickable ✕ icon on the right side of each token to allow removal
- [ ] P1: Attachment drawer needs to support two types: **files** (rendered as tokens) and **images** (rendered as 64×64px thumbnails in a horizontally scrollable carousel). On hover, image thumbnails should show a drop shadow and a dismiss button in the top corner. See [reference mockup](https://github.com/facebookexperimental/xds/issues/1226) for expected layout
- [ ] P1: Drawer collapse/expand animation is incorrect — the collapsed label and expanded content should use a dissolve (crossfade) transition only, with no additional motion inside the drawer
- [ ] P1: Status banner should always appear at the bottom of the composer — should not stack on top of the drawer

### XDSChatComposerInput

- [ ] P0: Placeholder text does not reappear after users delete all content from the input
- [ ] P1: File paste should always render the attachment in the composer drawer

### XDSChatMessageList

- [ ] P0: "Scroll to bottom" button shows a cropped letter instead of only the icon when the page is scrolled
- [ ] P1: Message responses should not have grey bubble shapes by default — should be flat unless bubbles are specifically opted into
- [ ] P1: "Minimal" should be the default treatment. Current "Standard" variant should be renamed to indicate it includes names and avatars — "Minimal" (no names/avatars) is the expected default ([Storybook](https://studious-broccoli-o7e61n3.pages.github.io/storybook/index.html?path=/story/chat-xdschatmessagelist--standard))

### Reasoning & Tool Calls *(pre-merge)*

- [x] P1: Tool Calls icon is not recognizable — should use a wrench icon
- [x] P1: Expand/collapse arrow for tool call groups is positioned on the far right — should be immediately to the right of the label text
- [x] P1: Expand/collapse arrow direction is wrong — should point up when expanded and down when collapsed
- [x] P1: Insufficient spacing between the response message and the reasoning/tool calls section
- [x] P1: Individual tool call status icons should align with the "Tool Calls" icon, and all text labels should be aligned

### PR DESCRIPTION
**Pull request by cixzhang**
## What

Chat component hardening, new features, and a full composition story.

### Hardening (#1226)
| Finding | P | Fix |
|---------|---|-----|
| Scroll-to-bottom shows cropped letter | P0 | Icon-only when no new messages |
| Drawer collapse animation | P1 | Staggered fade + slide |
| statusPosition removed | P1 | Always bottom |
| Assistant stories use flat text | P1 | Stories use XDSMarkdown directly |
| Default/Detailed story rename | P1 | Minimal is default |
| Code blocks overflow on mobile | P1 | minWidth: 0 on Markdown root |
| Tool call icons from registry | P1 | wrench + check/close with color: inherit |
| Tool call no indent | P1 | Removed list padding |
| Spinner jitter | P1 | Even frame size for canvas |
| Bubble radius | P1 | radius-page |

### Tool Calls Redesign
- Surface shows latest call + count + chevron (collapsed)
- Expanded shows "N tool calls" label with full list
- `label` renamed to `target` on items
- `onClick` replaced with `resultDetail` for inline disclosure
- `stats` split: `additions`/`deletions` (colored) + free-form `stats` ReactNode
- `XDSChatToolCallStats` removed
- Spinner uses `shade="subtle"` (new: muted secondary color, thinner sm border)
- Status icons: check/close from registry in muted circle, color: inherit

### New Features
- **XDSChatComposerInputHandle** — imperative ref: insertToken, insertText, focus, getValue
- **XDSChatMessageTokenizedText** — renders @mention patterns as inline badges
- **XDSProgressBar variant="neutral"** — muted fill for context meters
- **XDSSpinner shade="subtle"** — less prominent for inline use

### Composition Story
Full-page AI chat: phased streaming, tool calls with inline result details, @/command triggers, file attachments, context meter with tooltip, frosted glass composer

### Moved to Lab
- XDSChatReasoning → packages/lab (not production-ready yet)

Partially closes #1226

### CODE REVIEW

File: packages/core/src/Chat/XDSChatToolCalls.tsx [hunk 1]
```diff
@@ -347,7 +347,15 @@ function ErrorIcon() {
 
 function WrenchIcon() {
```
Comment (cixzhang) [inline packages/core/src/Chat/XDSChatToolCalls.tsx]: Move this into the icon registry

File: packages/core/src/Chat/XDSChatToolCalls.tsx
Comment (cixzhang) [inline packages/core/src/Chat/XDSChatToolCalls.tsx]: Use the one from the icon registry

Comment (cixzhang) [inline packages/core/src/Chat/XDSChatToolCalls.tsx]: Use the icon registry

Comment (cixzhang) [inline packages/core/src/Chat/XDSChatToolCalls.tsx]: Why this extra div

Comment (cixzhang) [inline packages/core/src/Chat/XDSChatToolCalls.tsx]: Should we use XDSSpinner

File: packages/core/src/Chat/XDSChatMessageList.tsx [hunk 2]
```diff
@@ -140,17 +140,20 @@ const styles = stylex.create({
   },
   gapCompact: {
     gap: spacingVars['--spacing-2'],
-    paddingBlock: spacingVars['--spacing-2'],
+    paddingBlockStart: spacingVars['--spacing-2'],
+    paddingBlockEnd: spacingVars['--spacing-4'],
```
Comment (cixzhang) [inline packages/core/src/Chat/XDSChatMessageList.tsx]: We can probably undo this. The chat layout should have extra space in the bottom to clear the composer plus some breathing room

File: packages/core/src/Chat/XDSChatComposer.tsx [hunk 3]
```diff
@@ -238,13 +236,6 @@ const styles = stylex.create({
     lineHeight: typeScaleVars['--text-supporting-leading'],
     fontFamily: typographyVars['--font-family-body'],
   },
-  statusTop: {
```
Comment (cixzhang) [inline packages/core/src/Chat/XDSChatComposer.tsx:241]: We decided that we'll actually keep a top positioned status after all

File: apps/storybook/stories/ChatComposition.stories.tsx [hunk 4]
```diff
@@ -0,0 +1,495 @@
...
+                    size="sm"
+                    icon={PaperclipIcon}
+                    iconOnly
+                    onClick={() =>
+                      setFiles(prev => [...prev, `file-${prev.length + 1}.tsx`])
+                    }
+                  />
+                </>
+              }
+              headerContext={
```
Comment (cixzhang) [inline apps/storybook/stories/ChatComposition.stories.tsx:486]: I'm not seeing this in the story
