### PR TITLE
fix: make multi-selector checkboxes decorative to fix label click toggle

### LINKED ISSUE #1072: Bug: Clicking label in multi-selector items doesn't toggle checkbox
## Description

In the multi-selector menu items, clicking the label text does not toggle the checkbox. Only clicking the checkbox input itself works.

## Root Cause

The multi-selector items currently use `XDSCheckboxInput` with its built-in label, which creates a standard `<label>` + `<input>` association. However, these items should be `role="option"` inside a multi-option listbox menu — the checkboxes are **decorative only** (indicating selection state), not interactive form controls.

Because the label is associated with the checkbox input rather than the list option behavior, clicking the label toggles the checkbox natively but doesn't go through the selector's selection logic, causing a mismatch.

## Proposed Fix

- Don't use `XDSCheckboxInput`'s label directly for the item text
- The checkbox should be purely decorative (`aria-hidden`), reflecting the selection state from `XDSSelector`
- Reuse the selection state from `XDSSelector` so the entire item row handles the toggle, keeping the checkbox visual in sync
- Ensure the items use `role="option"` with `aria-selected` for proper listbox semantics

### PR DESCRIPTION
**Pull request by cixzhang**
## Summary

Fixes #1072

- Clicking the label text in multi-selector items caused a double-toggle (no net change) because the native `<label>`→`<input>` association fired a synthesized click that bubbled to the parent alongside the original click, calling `handleToggle` twice
- Made `XDSCheckboxInput` purely decorative inside multi-selector items by wrapping it in `aria-hidden="true"` + `pointer-events: none` containers
- Rendered item label text in a separate `<span>` outside the checkbox component
- Applied the same fix to the "select all" row
- Updated tests to query by text content instead of label association

## Test plan

- [x] All 32 existing multi-selector tests pass
- [x] Manually verify clicking anywhere on a multi-selector item row (including label text) toggles the checkbox
- [x] Verify "select all" label click works correctly
- [x] Verify keyboard navigation still works (Enter/Space to toggle)
- [x] Verify screen reader announces items as `role="option"` with `aria-selected` state

### CODE REVIEW

**Comment by cixzhang** [comment]
Keyboard navigation should follow combobox pattern.

File: packages/core/src/MultiSelector/XDSMultiSelector.tsx [hunk 1]
```diff
@@ -805,108 +866,122 @@ export function XDSMultiSelector<T extends XDSMultiSelectorOptionType>({
...
-            label={children ? '' : (item.label ?? item.value)}
-            isLabelHidden={!!children}
-            value={isSelected}
-            onChange={() => {}}
-            isDisabled={item.disabled}
-            size={size === 'lg' ? 'md' : size}
-          />
-          {children && children(item)}
+          <div inert {...stylex.props(styles.checkboxDecorative)}>
+            <XDSCheckboxInput
```
Comment (cixzhang) [inline packages/core/src/MultiSelector/XDSMultiSelector.tsx:884]: Are we able to apply inert directly on the checkbox input and save a dom element? Also checkboxDecorative may not be necessary as a result.
