### PR TITLE
fix(Dialog): propagate maxHeight to layout via --container-max-height (#905)

### LINKED ISSUE #905: fix(Dialog): scrolling content does not scroll when maxHeight is set
## Problem

When a Dialog has `maxHeight` set (e.g. `maxHeight="50vh"`) and content exceeds that height, the content area does not scroll. The header and footer should stay fixed while `XDSLayoutContent` scrolls internally, but instead the content is just clipped by `overflow: hidden` on the dialog.

## Root Cause

Native `<dialog>` with `showModal()` gets UA style `height: fit-content`. This makes `height: fit-content` a non-definite value in CSS spec terms, so `height: 100%` on children (XDSLayout uses `height: calc(100% + ...)` in fill mode) resolves to `auto` instead of the dialog constrained height.

The chain breaks like this:
1. Dialog: `height: fit-content` (UA), `maxHeight: 450px` (from prop), `overflow: hidden` - computes to 450px tall
2. XDSLayout (child): `height: calc(100% + ...)` - 100% resolves to auto because parent height is `fit-content`, blows out to 3186px
3. XDSLayoutContent: `overflow: auto` - never activates because its parent is already full content height

## What works (tested via Playwright)

Setting `maxHeight` and `overflow: hidden` directly on the XDSLayout DOM nodes (first two levels below dialog) via inline styles makes scrolling work AND keeps short dialogs content-sized. This was verified with both a scrolling story (450px, footer visible, content scrolls) and default story (stays at ~230px).

Setting `height: 100%` on the dialog itself also fixes scrolling, but makes ALL dialogs fill the viewport (182px dialog becomes 900px).

## What does NOT work

| Approach | Result |
|----------|--------|
| `height: 100%` on dialog | Fixes scroll but short dialogs fill viewport |
| `height: min(fit-content, maxHeight)` | Short dialogs stay small but scroll still broken |
| `height: fit-content(maxHeight)` | Same, no scroll |
| `overflow: clip` instead of `hidden` | Still no scroll |
| Remove `overflow: hidden` | Dialog itself scrolls (whole thing including header/footer) |
| `display: grid` instead of `flex` | Same issue, layout still blows out |
| Inner wrapper div with `maxHeight: inherit` | `inherit` resolves to `fit-content`, not the computed pixel value |
| Inner wrapper div with explicit maxHeight | Wrapper is constrained but XDSLayout height:100% still resolves against fit-content |
| CSS container queries (`100cqb`) | Breaks dialog sizing entirely |

## Likely fix

This probably needs a change in how XDSLayout resolves its height when inside a dialog (or any `fit-content` parent). Options:

1. XDSLayout could use `max-height: inherit` + `overflow: hidden` when inside a dialog context
2. XDSDialog could pass maxHeight as a CSS custom property that XDSLayout reads
3. XDSLayout fill mode could avoid relying on `height: calc(100% + ...)` and use `flex: 1; min-height: 0` instead (may be the cleanest fix)

## Repro

Open the Scrolling Content story in Storybook: `core-xdsdialog--scrolling-content`

The 20 paragraphs of lorem ipsum should scroll within the dialog while header and footer stay fixed. Currently the content is just clipped.

Hardening: #718

### PR DESCRIPTION
**Pull request by cixzhang**
## Problem

The dialog uses `maxHeight` (default `'75vh'`) with `height: fit-content`, so percentage-based heights in the XDSLayout chain never resolve to a definite value. The layout's `fill` mode uses `height: calc(100% + ...)` which needs a definite parent height to work. Result: scrollable content doesn't scroll.

## Solution

Introduce a `--container-max-height` CSS custom property that containers can set to communicate their height constraint to XDSLayout.

### Changes

**`XDSDialog.tsx`** — Sets `--container-max-height` on the `inner` div, passing through the dialog's `maxHeight` prop value. Skipped for fullscreen dialogs.

**`XDSLayout.tsx`** — The `fill` style now reads `max-height: var(--container-max-height, none)`. When a container sets the var, the layout constrains itself. When unset, `none` preserves existing behavior.

This is a general-purpose mechanism — any container (Card, Section, etc.) can set `--container-max-height` to enable scroll containment in nested layouts.

Closes #905

---

### CODE REVIEW

File: packages/core/src/Dialog/XDSDialog.tsx [hunk 1]
```diff
@@ -160,6 +160,10 @@ const dynamicStyles = stylex.create({
     maxWidth: '90vw',
     maxHeight: typeof maxHeight === 'number' ? `${maxHeight}px` : maxHeight,
   }),
+  containerMaxHeight: (maxHeight: number | string) => ({
```
Comment (cixzhang) [inline packages/core/src/Dialog/XDSDialog.tsx]: This is pretty simple but can we make it part of the container system instead of having it out at the dialog level? That way the layer can just pay attention to it's integration with containers instead of needing to consider each container separately.

File: packages/core/src/Dialog/XDSDialog.tsx [hunk 2]
```diff
@@ -378,7 +378,14 @@ export function XDSDialog({
       {...mergeProps(
         xdsClassName('dialog', {variant}),
         stylex.props(
-          ...container({padding: 'spacing0'}),
+          ...container({
+            padding: 'spacing0',
+            maxHeight: isFullscreen
+              ? undefined
```
Comment (cixzhang) [inline packages/core/src/Dialog/XDSDialog.tsx:384]: I wonder if this needs to be 100dvh. Can we add more content to the full screen story to verify?
